[package]
name = "rust_nonogram_solver"
version = "0.1.0"
authors = ["Henrik Hellenborg <henrik@hellenborg.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
